# Домашнее задание "Линейная алгебра. Матрицы".

## Уровень 0:


### Задание 1

 - Создайте матрицу 3 на 3, заполненную числами от 1 до 9
 - Прибавьте к ней матрицу с единицами на диагонале
 - Умножьте полученную матрицу на вектор (1, 2, 3)
 - Вычислить транспонированную матрицу $A^T$ от полученной в результате прибавления матрицы
 - Посчитайте обратную матрицу к полученной в результате прибавления матрице


In [7]:
import numpy as np

# Создайте матрицу 3 на 3, заполненную числами от 1 до 9
matrix_1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

# Единичная матрица
one_matrix = np.eye(3,3)

# Вектор (1, 2, 3)
vector_1 = np.array([1,2,3])

In [4]:
# Сложим две матрицы
answer = matrix_1 + one_matrix
answer

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [18]:
# Умножаем матрицу на вектр
answer@vector_1

array([15., 34., 53.])

In [9]:
# Транспонированная матрица
np.transpose(answer)

array([[ 2.,  4.,  7.],
       [ 2.,  6.,  8.],
       [ 3.,  6., 10.]])

In [15]:
# Обратая матрица
np.linalg.inv(answer)

array([[-6.00000000e+00, -2.00000000e+00,  3.00000000e+00],
       [-1.00000000e+00,  5.00000000e-01, -2.33146835e-16],
       [ 5.00000000e+00,  1.00000000e+00, -2.00000000e+00]])

In [20]:
# Проверим и убедимся, что в результате умножения получим единичную матрицу
answer_inv = np.linalg.inv(answer)

answer@answer_inv

array([[ 1.00000000e+00, -3.33066907e-16,  6.66133815e-16],
       [-5.32907052e-15,  1.00000000e+00,  1.33226763e-15],
       [-1.77635684e-15, -1.11022302e-15,  1.00000000e+00]])

## Уровень 1:

### Задание 2

Найдите собственные значения и собственные вектора матрицы:
```
m = np.array([[2, 2],
              [1, 3]])
print(m)
```



In [21]:
m = np.array([[2, 2],[1, 3]])
m

array([[2, 2],
       [1, 3]])

In [22]:
# Собственное значение

np.linalg.eigvals(m)

array([1., 4.])

In [26]:
# Собственные векторы

np.linalg.eig(m)[1]

array([[-0.89442719, -0.70710678],
       [ 0.4472136 , -0.70710678]])

In [34]:
# Приведем векторы к "красивому" виду

vecs = np.transpose(np.linalg.eig(m)[1])

vecs

array([[-0.89442719,  0.4472136 ],
       [-0.70710678, -0.70710678]])

In [36]:
vecs[0]/0.4472136

array([-1.99999998,  0.99999999])

In [37]:
vecs[1]/-0.70710678

array([1., 1.])

### Задание 3


Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2! 

In [12]:
# Пример такой матрицы 2х2
matrix_2 = np.array([[4,3],[5,4]])
matrix_2

array([[4, 3],
       [5, 4]])

In [14]:
np.linalg.det(matrix_2)

1.0000000000000009